# Generated by Django 3.0.7 on 2020-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bothajax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpasswordrequest',
            name='token',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
