# Generated by Django 3.0.7 on 2020-06-17 14:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('role', models.CharField(choices=[('J', 'Junior'), ('S', 'Senior')], default='J', max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            managers=[
                ('all_employees', django.db.models.manager.Manager()),
            ],
        ),
    ]
