# Generated by Django 3.0.7 on 2020-06-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_employee'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
