# Generated by Django 3.0.7 on 2020-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_auto_20200617_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
