# Generated by Django 3.0.7 on 2020-06-18 09:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_employee_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('admin_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
