# Generated by Django 3.0.7 on 2020-07-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
    ]
