# Generated by Django 3.0.7 on 2020-07-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0002_remove_person_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
