# Generated by Django 3.0.7 on 2020-06-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0004_auto_20200618_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QueryApp.Blog')),
                ('theme', models.CharField(max_length=30)),
            ],
            bases=('QueryApp.blog',),
        ),
    ]
