# Generated by Django 3.0.7 on 2020-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0004_auto_20200707_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
