# Generated by Django 3.0.7 on 2020-06-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0005_themblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThemBlog',
            new_name='ThemeBlog',
        ),
    ]
