# Generated by Django 3.0.7 on 2020-06-20 14:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0008_auto_20200620_1338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
