# Generated by Django 3.0.7 on 2020-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0009_auto_20200620_1406'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
