# Generated by Django 3.0.7 on 2020-06-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0011_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='filesize',
            new_name='upload',
        ),
    ]
