# Generated by Django 3.0.7 on 2020-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0011_auto_20200708_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='file',
        ),
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl', 'Dutch')], default='en-us', max_length=5),
        ),
    ]
