# Generated by Django 3.0.7 on 2020-06-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0013_auto_20200623_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
