# Generated by Django 3.0.7 on 2020-06-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0016_choice_historicalchoice_historicalpoll_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='historicalchoice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchoice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='historicalpoll',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Photoupload',
        ),
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='HistoricalChoice',
        ),
        migrations.DeleteModel(
            name='HistoricalPoll',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
