# Generated by Django 3.0.7 on 2020-06-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryApp', '0023_remove_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
